PythonWeb/petstagram/petstagram/accounts/urls.py
from django.urls import path, include

from petstagram.accounts.views import register, login, show_profile_details, edit_profile, delete_profile

urlpatterns = (
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('profile/<int:pk>/', include([
        path('', show_profile_details, name='profile-details'),
        path('edit/', edit_profile, name='profile-edit'),
        path('delete/', delete_profile, name='profile-delete'),
    ]))
)

PythonWeb/petstagram/petstagram/common/urls.py
from django.urls import path

from petstagram.common.views import home, like_functionality, copy_link_to_clipboard

urlpatterns = (
    path('', home, name='home'),
    path('like/<int:photo_id>/', like_functionality, name='like'),
    path('share/<int:photo_id>/', copy_link_to_clipboard, name='share'),

)

PythonWeb/petstagram/petstagram/pets/urls.py
from django.urls import path

from petstagram.pets.views import add_pet, show_pet_details, edit_pet, delete_pet

urlpatterns = (
    path('add/', add_pet, name='add-pet'),
    path('<str:username>/pet/<slug:pet_name>/', show_pet_details, name='pet-details'),
    path('<str:username>/pet/<slug:pet_name>/edit/', edit_pet, name='pet-edit'),
    path('<str:username>/pet/<slug:pet_name>/delete/', delete_pet, name='pet-delete'),

)

PythonWeb/petstagram/petstagram/photos/urls.py
from django.urls import path

from petstagram.photos.views import add_photo, show_photo_details, edit_photo

urlpatterns = (
    path('add/', add_photo, name='add-photo'),
    path('<int:pk>/', show_photo_details, name='show-photo-details'),
    path('<int:pk>/edit/', edit_photo, name='photo-edit'),

)

PythonWeb/petstagram/petstagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('petstagram.common.urls')),
    path('accounts/', include('petstagram.accounts.urls')),
    path('pets/', include('petstagram.pets.urls')),
    path('photos/', include('petstagram.photos.urls')),

]

PythonWeb/petstagram/petstagram/common/models.py
from django.db import models

from petstagram.photos.models import Photo


class Comment(models.Model):
    MAX_TEXT_LENGTH = 300

    comment_text = models.TextField(
        max_length=MAX_TEXT_LENGTH,
    )
    date_time_of_publication = models.DateTimeField(auto_now_add=True)
    to_photo = models.ForeignKey(
        Photo,
        on_delete=models.CASCADE,
        null=False,
        blank=True
    )

    class Meta:
        ordering = ['-date_time_of_publication']


class Like(models.Model):
    to_photo = models.ForeignKey(
        Photo,
        on_delete=models.CASCADE,
        null=False,
        blank=True
    )

PythonWeb/petstagram/petstagram/pets/models.py
from django.db import models
from django.template.defaultfilters import slugify


class Pet(models.Model):
    MAX_NAME_LENGTH = 30

    name = models.CharField(
        max_length=MAX_NAME_LENGTH,
    )
    personal_photo = models.URLField()

    date_of_birth = models.DateField(
        blank=True,
        null=True
    )
    slug = models.SlugField(
        unique=True,
        blank=True,
        editable=False,
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(f"{self.name}-{self.id}")
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name

PythonWeb/petstagram/petstagram/photos/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from petstagram.pets.models import Pet
from petstagram.photos.validators import validate_file_size


class Photo(models.Model):
    MIN_DESCRIPTION_LENGTH = 10
    MAX_DESCRIPTION_LENGTH = 300
    MAX_LOCATION_LENGTH = 30

    photo = models.ImageField(
        upload_to='mediafiles/pet_photos/',
        validators=(validate_file_size, )
    )

    description = models.TextField(
        max_length=MAX_DESCRIPTION_LENGTH,
        validators=(MinLengthValidator(MIN_DESCRIPTION_LENGTH),),
        null=True,
        blank=True,
    )
    location = models.CharField(
        max_length=MAX_LOCATION_LENGTH
    )

    date_of_publication = models.DateField(auto_now=True)

    tagged_pets = models.ManyToManyField(
        Pet,
    )

PythonWeb/petstagram/petstagram/accounts/views.py
from django.shortcuts import render


def register(request):
    return render(request, 'accounts/register-page.html')


def login(request):
    return render(request, 'accounts/login-page.html')


def show_profile_details(request, pk):
    return render(request, 'accounts/profile-details-page.html')


def edit_profile(request):
    return render(request, 'accounts/profile-edit-page.html')


def delete_profile(request):
    return render(request, 'accounts/profile-details-page.html')

PythonWeb/petstagram/petstagram/common/views.py
from django.shortcuts import render, resolve_url, redirect
from pyperclip import copy

from petstagram.common.models import Like
from petstagram.photos.models import Photo


def home(request):
    all_photos = Photo.objects.all()

    context = {'all_photos': all_photos}
    return render(request, 'common/home-page.html', context)


def like_functionality(request, photo_id):
    photo = Photo.objects.get(id=photo_id)
    liked_object = Like.objects.filter(to_photo_id=photo_id).first()

    # photo_like = Like(id=photo_id)
    # photo_like.save()

    # Like.objects.create(id=photo_id)

    if liked_object:
        liked_object.delete()
    else:
        like = Like(to_photo=photo)
        like.save()

    return redirect(request.META['HTTP_REFERER'] + f'#{photo_id}')


def copy_link_to_clipboard(request, photo_id):
    copy(request.META['HTTP_HOST'] + resolve_url('show-photo-details', photo_id))
    return redirect(request.META['HTTP_REFERER'] + f'#{photo_id}')

PythonWeb/petstagram/petstagram/pets/views.py
from django.shortcuts import render

from petstagram.pets.models import Pet
from petstagram.photos.models import Photo


def add_pet(request):
    return render(request, 'pets/pet-add-page.html')


def show_pet_details(request, username, pet_slug):
    pet = Pet.objects.get(slug=pet_slug)
    all_photos = pet.photo_set.all()
    context = {
        'pet': pet,
        'all_photos': all_photos
    }
    return render(request, 'pets/pet-details-page.html', context)


def edit_pet(request):
    return render(request, 'pets/pet-edit-page.html')


def delete_pet(request):
    return render(request, 'pets/pet-delete-page.html')

PythonWeb/petstagram/petstagram/photos/views.py
from django.shortcuts import render

from petstagram.photos.models import Photo


def add_photo(request):
    return render(request, 'photos/photo-add-page.html')


def show_photo_details(request, pk):
    photo = Photo.objects.get(id=pk)
    likes = photo.like_set.all()
    comments = photo.comment_set.all()

    context = {
        'photo': photo,
        'likes': likes,
        'comments': comments
    }

    return render(request, 'photos/photo-details-page.html', context)


def edit_photo(request):
    return render(request, 'photos/photo-edit-page.html')

PythonWeb/petstagram/petstagram/accounts/templates/accounts/login-page.html
{% extends 'base.html' %}

{% block content %}
<!-- Starts Main Section -->
<main>

    <!-- Start Login Section-->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Login Form-->
            <form action="#">
                <p>
                    <label for="id_username">Username:</label>
                    <input type="text" placeholder="Username">
                </p>
                <p>
                    <label for="id_password">Password:</label>
                    <input type="password" placeholder="Password">
                </p>

                <!-- Login Button-->
                <button type="submit">Log in</button>
            </form>
            <!-- End Login Form -->

        </div>
        <div class="second-option">

            <!-- Link to Register Page-->
            <p>Don't have account? <a href="#">Register</a></p>
        </div>
    </div>
    <!-- End Login Section-->

</main>
<!-- End Main Section -->

{% endblock %}

PythonWeb/petstagram/petstagram/accounts/templates/accounts/profile-delete-page.html
{% extends 'base.html' %}

{% block content %}
<!-- Starts Main Section -->
<main>

    <!-- Start Delete Profile Section -->
        <div class="delete-profile">
            <h1>
                Are you sure you want to delete your profile?
            </h1>
            <div class="sure-buttons">
                <!-- Yes (Delete Profile) Button -->
                <button>Yes</button>
                <!-- Go Back Button -->
                <a class="edit-btn" href="javascript:history.back()">Go Back</a>
            </div>
            <img src="/staticfiles/images/are_you_sure_cat.gif" alt="are you sure cat git">
        </div>
    <!-- End Delete Profile Section -->

</main>
<!-- End Main Section -->

{% endblock %}

PythonWeb/petstagram/petstagram/accounts/templates/accounts/profile-details-page.html
{% extends 'base.html' %}

{% block content %}
<!-- Starts Main Section -->
<main>

    <!-- Start Profile Details Section -->
    <div class="profile">

        <!-- Start Profile Personal Data Section -->
        <div class="profile-data">
            <div class="profile_img">
                <div class="image">

                    <!-- Profile Image -->
                    <img src="/staticfiles/images/person.png" alt="img8">
                </div>
            </div>
            <div class="personal">
                <div class="edit">
                    <!-- User Username -->
                    <p>d_kalaydzhiev</p>

                    <!-- IF the viewer is the owner of the profile -->
                    <!-- Link to Edit Profile Page -->
                    <a href="#">
                        <img class="edit-img" src="/staticfiles/images/edit-pen-icon-6.jpg" alt="edit button">
                    </a>

                    <!-- Link to Delete Profile Page -->
                    <a href="">
                        <img class="bin-img" src="/staticfiles/images/icon-remove-22.jpg" alt="bin button">
                    </a>
                    <!-- End IF the viewer is the owner of the profile -->

                </div>
                <div class="data">

                    <!-- Total Number of Photos by the User -->
                    <span>4</span>
                    <p>photos</p>

                    <!-- Total Number of Pets owned by the User -->
                    <span>7</span>
                    <p>pets</p>

                    <!-- Total Number of Likes for the User -->
                    <span>436</span>
                    <p>likes</p>
                </div>
                <!-- User First and Last Name IF Added -->
                <h3 class="names">Diyan Kalaydziev</h3>

                <!-- User Email Address -->
                <p class="email">d.denov@gmail.com</p>

                <!-- User Gender IF Added -->
                <p class="gender">Male</p>
            </div>
        </div>
        <!-- End Profile Personal Data Section -->

        <!-- Start Pets Data Section -->
        <div class="pets">
            <div class="statuses">

                <!-- Start 1st Pet Details Page -->
                <!-- Link to First Pet Details Page -->
                <a href="#">
                    <div class="head-pet">
                        <div class="status">
                            <div class="image">
                                <!-- Pet Image -->
                                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgoIHq82qLYnvomfz5ZkW5CLQ8VNxCyI-hUw&usqp=CAU"
                                     alt="pet img">
                            </div>
                        </div>
                        <!-- Pet Name -->
                        <p>Sasho</p>
                    </div>
                </a>
                <!-- End 1st Pet Details Page -->

                <!-- Start 2nd Pet Details Page -->
                <!-- Link to Second Pet Details Page -->
                <a href="#">
                    <div class="head-pet">
                        <div class="status">
                            <div class="image">
                                <!-- Pet Image -->
                                <img src="https://cdn.pixabay.com/photo/2016/12/13/05/15/puppy-1903313__340.jpg"
                                     alt="pet img">
                            </div>
                        </div>
                        <!-- Pet Name -->
                        <p>Todi</p>
                    </div>
                </a>
                <!-- End 2nd Pet Details Page -->

                <!-- Start 3rd Pet Details Page -->
                <!-- Link to Pet Details Page -->
                <a href="#">
                    <div class="head-pet">
                        <div class="status">
                            <div class="image">
                                <img src="https://images.unsplash.com/photo-1611003228941-98852ba62227?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmFieSUyMGRvZ3xlbnwwfHwwfHw%3D&w=1000&q=80"
                                     alt="pet img">
                            </div>
                        </div>
                        <p>Mihail</p>
                    </div>
                </a>
                <!-- End 3rd Pet Details Page -->

                <!-- Start 4th Pet Details Page -->
                <!-- Link to Pet Details Page -->
                <a href="#">
                    <div class="head-pet">
                        <div class="status">
                            <div class="image">
                                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/1200px-Cat03.jpg"
                                     alt="pet img">
                            </div>
                        </div>
                        <p>Petar</p>
                    </div>
                </a>
                <!-- End 4th Pet Details Page -->

                <!-- Start 5th Pet Details Page -->
                <!-- Link to Pet Details Page -->
                <a href="#">
                    <div class="head-pet">
                        <div class="status">
                            <div class="image">
                                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdKYe00NaD5SQjIMvXYPssq0r1dXJggL3ZIg&usqp=CAU"
                                     alt="pet img">
                            </div>
                        </div>
                        <p>Stamat</p>
                    </div>
                </a>
                <!-- End 5th Pet Details Page -->

                <!-- Start 6th Pet Details Page -->
                <!-- Link to Pet Details Page -->
                <a href="#">
                    <div class="head-pet">
                        <div class="status">
                            <div class="image">
                                <img src="https://cf.ltkcdn.net/small-pets/images/orig/278587-1600x1066-goldfish-swimming-in-fish-tank.jpg"
                                     alt="pet img">
                            </div>
                        </div>
                        <p>Toni</p>
                    </div>
                </a>
                <!-- End 6th Pet Details Page -->

                <!-- Start 7th Pet Details Page -->
                <!-- Link to Pet Details Page -->
                <a href="#">
                    <div class="head-pet">
                        <div class="status">
                            <div class="image">
                                <img src="https://i.pinimg.com/736x/01/6f/72/016f72c5812e1b8f71bdbf19d8c7558b.jpg"
                                     alt="pet img">
                            </div>
                        </div>
                        <p>Daisy</p>
                    </div>
                </a>
                <!-- End 7th Pet Details Page -->

            </div>
        </div>
        <!-- End Pets Data Section -->

        <!-- Start Last Uploaded Photos Section -->
        <div class="pet-photos">

            <!-- Link to Last Uploaded Pet Photo -->
            <a href="#">
                <!-- Pet Photo -->
                <img src="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631"
                     alt="pet img">
            </a>

            <!-- Link to Uploaded Pet Photo -->
            <a href="#">
                <!-- Pet Photo -->
                <img src="https://cf.ltkcdn.net/small-pets/images/orig/278587-1600x1066-goldfish-swimming-in-fish-tank.jpg"
                     alt="pet img">
            </a>

            <!-- Link to Uploaded Pet Photo -->
            <a href="#">
                <!-- Pet Photo -->
                <img src="https://thumbs.dreamstime.com/b/small-golden-retriever-puppy-6482030.jpg" alt="pet img">
            </a>

            <!-- Link to  Uploaded Pet Photo -->
            <a href="#">
                <!-- Pet Photo -->
                <img src="https://i.pinimg.com/originals/4e/55/83/4e5583748bc4000805df50e4ebcafffc.png" alt="pet img">
            </a>
        </div>
        <!-- End Last Uploaded Photos Section -->

    </div>
    <!-- End Profile Details Section -->

</main>
{% endblock %}

PythonWeb/petstagram/petstagram/accounts/templates/accounts/profile-edit-page.html
{% extends 'base.html' %}

{% block content %}
<!-- Starts Main Section -->
<main>
    <!-- Start Edit Profile Section -->
    <div class="edit-delete">
        <h2>Edit Profile</h2>
        <!-- Start Edit Profile From -->
        <form action="">
            <div class="label-input">
                <label for="first name">First name: </label>
                <input type="text" placeholder="First name" value="Diyan">
            </div>
            <br>
            <div class="label-input">
                <label for="last name">Last name: </label>
                <input type="text" placeholder="Last name" value="Kalayadzhiev">
            </div>
            <br>
            <div class="label-input">
                <label for="username">Username: </label>
                <input type="text" placeholder="Username" value="k_dido">
            </div>
            <br>
            <div class="label-input">
                <label for="email">Email: </label>
                <input type="email" placeholder="Email" value="d.denov@gmail.com">
            </div>
            <br>
            <div class="label-input">
                <label for="image">Image: </label>
                <input type="text" placeholder="Link to to profile picture"
                       value="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631">
            </div>
            <br>

            <div class="label-input">
                <label for="image">Gender: </label>
                <div class="list-choice">
                    <div class="list-choice-title">Gender</div>
                    <div class="list-choice-objects">
                        <label>
                            <input type="radio" name="gender"/> <span>Male</span>
                        </label>
                        <label>
                            <input type="radio" name="gender"/> <span>Female</span>
                        </label>
                        <label>
                            <input type="radio" name="gender"/> <span>Do not show</span>
                        </label>
                    </div>
                </div>
            </div>

            <!-- Edit Profile Button -->
            <button class="edit-btn" type="submit">Edit</button>
        </form>
        <!-- End Edit Profile Form -->

    </div>
    <!-- End Edit Profile Section -->

</main>
<!-- End Main Section -->
{% endblock %}

PythonWeb/petstagram/petstagram/accounts/templates/accounts/register-page.html
{% extends 'base.html' %}

{% block content %}
    <!-- Start Register Section -->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Register Form -->
            <form action="">
                <input type="text" placeholder="Username">

                <input type="email" placeholder="Email">

                <input type="password" placeholder="Password">

                <input type="password" placeholder="Repeat Password">

                <!-- Register Button -->
                <button type="submit">Register</button>
            </form>
            <!-- End Register Form -->

        </div>
        <div class="second-option">

            <!-- Link to Login Page -->
            <p>Have an account? <a href="#">Log in</a></p>
        </div>
    </div>
    <!-- End Register Section -->
{% endblock %}

PythonWeb/petstagram/petstagram/common/templates/common/home-page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Starts Main Section -->
    <main>
        <div class="container">
            <div class="col-9">

                <!-- Start Searchbar Form -->
                <form class="searchbar" method="post">
                    <input type="text" placeholder="Search by pet name...">
                    <button>
                        <img src="{% static 'images/search.png' %}" height="18" alt="img2">
                    </button>
                </form>
                <!-- End Searchbar Form -->
                {% include 'common/pets-posts.html' %}

            </div>
        </div>
    </main>
    <!-- End Main Section -->

{% endblock %}

PythonWeb/petstagram/petstagram/photos/templates/photos/photo-add-page.html
{% extends 'base.html' %}

{% block content %}

<!-- Starts Main Section -->
<main>
    <!-- Start Add Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Add photo</h2>
        <!-- Start Add Photo Form -->
        <form action="" enctype="multipart/form-data">
            <p>
                <label for="id_photo_file">Photo file:</label>
                <input type="file">
            </p>

            <p>
                <label for="id_description">Description:</label>
                <input type="text">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>
            <!-- Add Photo Button -->
            <button class="add-btn" type="submit">Add Photo</button>
        </form>
        <!-- End Add Photo Form -->
    </div>
    <!-- End Add Photo Section -->
</main>
<!-- End Main Section -->

{% endblock %}

PythonWeb/petstagram/petstagram/photos/templates/photos/photo-edit-page.html
{% extends 'base.html' %}
{% block content %}
<!-- Starts Main Section -->
<main>

    <!-- Starts Edit Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Edit photo</h2>

        <!-- Starts Edit Photo Form -->
        <form action="">
            <p>
                <label for="id_photo_file">Photo file:</label>
                <input type="file">
            </p>

            <p>
                <label for="id_description">Description:</label>
                <input type="text" value="Sasho is an Axolotl">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location"
                       value="Bansko, Bulgaria">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option selected>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>

            <!-- Edit Photo Button -->
            <button class="edit-btn" type="submit">Edit Photo</button>
        </form>
        <!-- End Edit Photo Form -->

    </div>
    <!-- End Edit Photo Section -->

</main>
<!-- End Main Section -->
{% endblock %}